### ISSUE TITLE
A Frame must be used to navigate to a Page

### ISSUE THREAD

**Issue by andipahlevy** [firescript/nativescript-contacts#43]
Please help, i get an error

my scripts:
```
let app = require( "application" );
let Permissions = require( "nativescript-permissions" );
let contacts = require('nativescript-contacts');
var imageSource = require( "image-source" );

var newContact = new contacts.Contact();
			newContact.name.given = "John";
			newContact.name.family = "Doe";
			newContact.phoneNumbers.push({ label: contacts.KnownLabel.HOME, value: "123457890" }); // See below for known labels
			newContact.save();
```

**Error log**
System.err: Calling js method onCreate failed
System.err:
System.err: Error: A Frame must be used to navigate to a Page.
System.err: File: "file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:163)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6342)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: A Frame must be used to navigate to a Page.
System.err: File: "file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     at android.app.Activity.performCreate(Activity.java:6847)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
System.err:     ... 9 more
ActivityManager: report kill process: killerPid is:3172, killedPid is:3172
ActivityManager: Process org.nativescript.application (pid 3172) has died: fore T
ActivityManager: cleanUpApplicationRecord -- 3172

**package.json**

{
  "name": "XXX",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "author": "Levi",
  "license": "MIT",
  "scripts": {
    "build": "webpack --env.tnsAction build",
    "build:android": "npm run build -- --env.android",
    "build:ios": "npm run build -- --env.ios",
    "debug": "webpack --watch --env.tnsAction debug",
    "debug:android": "npm run debug -- --env.android",
    "debug:ios": "npm run debug -- --env.ios",
    "watch": "webpack --watch --env.tnsAction run",
    "watch:android": "npm run watch -- --env.android",
    "watch:ios": "npm run watch -- --env.ios",
    "clean": "rimraf dist"
  },
  "dependencies": {
    "child_process": "^1.0.2",
    "nativescript-background-http": "^3.2.6",
    "nativescript-contacts": "^1.5.4",
    "nativescript-contacts-lite": "^0.2.5",
    "nativescript-exit": "^1.0.1",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-imagepicker": "^6.0.2",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-permissions": "^1.2.3",
    "nativescript-ripple": "^2.0.0",
    "nativescript-snackbar": "^3.1.0",
    "nativescript-socketio": "^2.5.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^1.3.1",
    "tns-core-modules": "~3.4.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.2.0",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.1",
    "nativescript-worker-loader": "^0.9.0",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0"
  }
}

**Comment by jzgoda** [comment]
@andipahlevy, did you ever get this worked out?
